language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - cp gorgonzola/settings_dev.py gorgonzola/settings.py
  - python manage.py gorgonzola_app.tests

